######################################################################
##
## Filename: cpu_tb.udo
## Created on: Tue Nov 17 18:18:02 China Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
