######################################################################
##
## Filename: dram_test.udo
## Created on: Mon Nov 30 13:38:56 China Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
