######################################################################
##
## Filename: imem_tb.udo
## Created on: Tue Dec 01 10:06:33 China Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
